server:
  port: 8772

#消息队列
spring:
  rabbitmq:
    host: 186.61.138.22
    port: 5671
    username: guest
    password: guest

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

env: test
branch: master